### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TuvixHosting** [ArthurJam/ruTorrent-plugin-sync#1]
Seems i cant get it to work
i installed on a seedbox and want to synch on ftp to another seedbox
nothing happens
all dependencies are installed, no errors showing

suggestions?

**Comment by ArthurJam** [comment]
Hi,

New torrents are not automatically sync.
You need to right click on torrent (or on a particular file) to program it.

If you know it, can you give me more informations.
What's your configuration : FTP or FTPS ; anonymous or user mode ; ...
Can you see the tasks in task list ?

**Comment by TuvixHosting** [comment]
i understand that you need to click the torrent etc...
i used ftp on port 21 to another seedbox in the folder /home/user/downloads
it is user mode set to user and password
i see the tasks in the list but it is not finishing them
if you like i can give you access to a test seedbox that i use so you can try

**Comment by ArthurJam** [comment]
Ok.
What do you see in the console output available in the task windows (double click on the list) ?
If you wish you can give me an access to your FTP.

**Comment by Merlincool** [comment]
> Ok.
> What do you see in the console output available in the task windows (double click on the list) ?
> If you wish you can give me an access to your FTP.

I am facing same issue if you can solve it. 

while ! /usr/bin/php '/var/www/rutorrent/plugins/sync/complete.php' 7780FEAAA181E7DB98FD852885BFD82CE619B12C 0 ; do sleep 30 ; done  
/usr/bin/curl 'ftp://MY.REMOTE.SERVER:21/Downloaded from www.ettv.to .txt' --user USERNAME\_OF\_MY\_REMOTE\_SERVER:PASSWORD --ftp-create-dirs --globoff --continue - --upload-file '/PATH/TO/DOWNLOAD/ON\_SEEDBOX/The.Walking.Dead.S10E04.WEB.H264-XLF\[ettv\]/Downloaded from www.ettv.to .txt'  

>
